# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Buildjob
    steps:
    - bash: echo "Build please"
- stage: DevDeploy
  jobs:
  - deployment: Devdeploy job
    environment: Dev
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo deploy to Dev
- stage: QADeploy
  jobs:
  - deployment: QAdeploy job
    environment: QA
    strategy:
     runOnce:
       deploy:
         steps:
         - script: echo deploy to QA
